In [28]:
import pandas as pd
import numpy as np
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
ratings=pd.read_csv('toy.csv',index_col=0)
ratings=ratings.fillna(0)

In [30]:
def standardize(row):
    new_row=((row- row.mean())/(row.max()-row.min()))
    return new_row
ratings_std= ratings.apply(standardize)
ratings_std

action1  action2   action3  romantic1  romantic2  romantic3
user 1     0.36      0.6  0.400000      -0.65      -0.08      -0.35
user 2     0.56      0.2  0.400000      -0.15      -0.08      -0.60
user 3    -0.24     -0.4 -0.600000       0.35       0.52       0.40
user 4    -0.44      0.0 -0.266667       0.35      -0.48       0.15
user 5    -0.24     -0.4  0.066667       0.10       0.12       0.40

In [20]:
item_similarity = cosine_similarity(ratings_std)
print(item_similarity)

[[ 1.          0.76409098 -0.83718317 -0.57786068 -0.7361606 ]
 [ 0.76409098  1.         -0.78062564 -0.60148288 -0.74685173]
 [-0.83718317 -0.78062564  1.          0.23334449  0.64173153]
 [-0.57786068 -0.60148288  0.23334449  1.          0.24550092]
 [-0.7361606  -0.74685173  0.64173153  0.24550092  1.        ]]


In [31]:
iitem_similarity = cosine_similarity(ratings_std.T)
print(iitem_similarity)

[[ 1.          0.70668875  0.81368151 -0.79941088 -0.02539184 -0.91410609]
 [ 0.70668875  1.          0.72310153 -0.84515425 -0.5189993  -0.84337386]
 [ 0.81368151  0.72310153  1.         -0.84794611 -0.3799803  -0.80218063]
 [-0.79941088 -0.84515425 -0.84794611  1.          0.14803913  0.72374686]
 [-0.02539184 -0.5189993  -0.3799803   0.14803913  1.          0.39393939]
 [-0.91410609 -0.84337386 -0.80218063  0.72374686  0.39393939  1.        ]]


In [34]:
itemsimilaritydf=pd.DataFrame(iitem_similarity,
                              index=ratings.columns,
                              columns=ratings.columns)
itemsimilaritydf


action1   action2   action3  romantic1  romantic2  romantic3
action1    1.000000  0.706689  0.813682  -0.799411  -0.025392  -0.914106
action2    0.706689  1.000000  0.723102  -0.845154  -0.518999  -0.843374
action3    0.813682  0.723102  1.000000  -0.847946  -0.379980  -0.802181
romantic1 -0.799411 -0.845154 -0.847946   1.000000   0.148039   0.723747
romantic2 -0.025392 -0.518999 -0.379980   0.148039   1.000000   0.393939
romantic3 -0.914106 -0.843374 -0.802181   0.723747   0.393939   1.000000

In [36]:
iitemsimilaritydf=pd.DataFrame(item_similarity,
                              index=ratings.index,
                              columns=ratings.index)
iitemsimilaritydf



user 1    user 2    user 3    user 4    user 5
user 1  1.000000  0.764091 -0.837183 -0.577861 -0.736161
user 2  0.764091  1.000000 -0.780626 -0.601483 -0.746852
user 3 -0.837183 -0.780626  1.000000  0.233344  0.641732
user 4 -0.577861 -0.601483  0.233344  1.000000  0.245501
user 5 -0.736161 -0.746852  0.641732  0.245501  1.000000

In [44]:
def get_similar_movies(movie_name,user_rating):
    similar_score = itemsimilaritydf[movie_name]*(user_rating-2.5)
    similar_score= similar_score.sort_values(ascending=False)
    
    return similar_score
print(get_similar_movies("romantic1",2))

action3      0.423973
action2      0.422577
action1      0.399705
romantic2   -0.074020
romantic3   -0.361873
romantic1   -0.500000
Name: romantic1, dtype: float64


In [53]:
action_lover=[("action1",5),("romantic2",2),("romantic3",2)]

similar_movies=pd.DataFrame()

for move,rati in action_lover:
    similar_movies=similar_movies.append(
        get_similar_movies(move,rati),ignore_index=True)
similar_movies.head()
similar_movies.sum().sort_values(ascending=False)

action1      2.969749
action3      2.625284
action2      2.447908
romantic2   -0.760449
romantic1   -2.434420
romantic3   -2.982235
dtype: float64